apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      nodeSelector:
        agentpool: case2pool
      containers:
      - name: app-2
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "900m"