apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hpa-deployment
  template:
    metadata:
      labels:
        run: hpa-deployment
    spec:
      containers:
      - name: hpa-deployment
        image: k8s.gcr.io/hpa-example
        resources:
          limits:
            memory: "16Mi"
            cpu: "20m"
          requests:
            memory: "12Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
