apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      nodeSelector:
        agentpool: case2pool
      containers:
      - name: app-1
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "700m"