# deployment of a pod with a single container running mas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobaia
  namespace: cobaia
  labels:
    app: cobaia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cobaia
  template:
    metadata:
      labels:
        app: cobaia
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "NoSchedule"
        effect: "NoSchedule"
      containers:
      - name: cobaia
        image: nginxx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2048m"