# deployment of a pod with a single container running mas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-deployment
  labels:
    app: mas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas
  template:
    metadata:
      labels:
        app: mas
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: mas
      containers:
      - name: mas
        image: mvpmas.azurecr.io/mas-app:v0.3
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: mas-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2048m"