# deployment of a pod with a single container running mas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-deployment
  labels:
    app: mas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas
  template:
    metadata:
      labels:
        app: mas
    spec:
      containers:
      - name: mas
        image: deividfoggi/mi6-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"