# a service to expose nginx deployment app in Azure Kubernetes Service (AKS) using Azure Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: mas-service
  labels:
    app: mas
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app: mas
